export const projectAction = {
    CREATE_PROJECT_REQUEST: "CREATE_PROJECT_REQUEST",
    CREATE_PROJECT_SUCCESS: "CREATE_PROJECT_SUCCESS",
    CREATE_PROJECT_FAILURE: "CREATE_PROJECT_FAILURE",

    GET_PROJECT_TREE_REQUEST: "GET_PROJECT_TREE_REQUEST",
    GET_PROJECT_TREE_SUCCESS: "GET_PROJECT_TREE_SUCCESS",
    GET_PROJECT_TREE_FAILURE: "GET_PROJECT_TREE_FAILURE",

    CLEAR_PROJECT_STATE:"CLEAR_PROJECT_STATE"
}