export const projectAction = {
    CREATE_PROJECT_REQUEST: "CREATE_PROJECT_REQUEST",
    CREATE_PROJECT_SUCCESS: "CREATE_PROJECT_SUCCESS",
    CREATE_PROJECT_FAILURE: "CREATE_PROJECT_FAILURE",

    CLEAR_PROJECT_STATE:"CLEAR_PROJECT_STATE"
}